spring:
  cloud: 
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**
            
        - id: products-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/** 
        
        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/transactionService/** 

            
        - id: carts-service
          uri: http://localhost:8080
          predicates:
            - Path=/cart/**, /orders/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true